var namespace_reddit_text_to_speech_1_1_logic_1_1_services_1_1_azure =
[
    [ "AzureAuthenticationService", "class_reddit_text_to_speech_1_1_logic_1_1_services_1_1_azure_1_1_azure_authentication_service.html", "class_reddit_text_to_speech_1_1_logic_1_1_services_1_1_azure_1_1_azure_authentication_service" ]
];